name: do commit

on:
  workflow_dispatch:

jobs:
  runcy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: ⚙️ Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: commit
        run: |
          B_NAME="$(uuidgen)"
          PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')

          echo 'a' >> text.text
          git add -A
          git commit -m "test: empty"

          git branch "$B_NAME"
          gh pr checkout "$PR_NUMBER"
          git cherry-pick "$B_NAME"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}