name: run cypress test

on:
  workflow_dispatch:

jobs:
  runcy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: trigger cypress test
        run: |
          gh workflow -R unknownOrganization/cypress-ci-test run integration.yaml -r main
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: list cypress test workflow
        run: |
          gh workflow -R unknownOrganization/cypress-ci-test list
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: wait for test success
        run: |
          gh run -R unknownOrganization/cypress-ci-test -w integration.yaml list
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}