name: run cypress test

on:
  workflow_dispatch:

jobs:
  runcy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: trigger cypress test
        run: |
          export NOWTIME=$(date +%s)
          gh workflow -R unknownOrganization/cypress-ci-test run integration.yaml -r main

          # gh api \
          # -H "Accept: application/vnd.github+json" \
          # -H "X-GitHub-Api-Version: 2022-11-28" \
          # /repos/unknownOrganization/cypress-ci-test/ray31245/actions/workflows
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: list cypress test workflow
        run: |
          gh workflow -R unknownOrganization/cypress-ci-test list
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: wait for test success
        run: |
          gh run -R unknownOrganization/cypress-ci-test --workflow integration.yaml --status="in_progress" --limit 1  list
          export RUN_INFO="null"
          until [ "$RUN_INFO" != "null" ]; do
            export RUN_INFO=$(gh run -R unknownOrganization/cypress-ci-test --workflow integration.yaml --status="in_progress" --limit 1  list --json name,conclusion,databaseId,workflowDatabaseId,createdAt,status | jq .[0])
          done
          echo $RUN_INFO
          echo $RUN_INFO | jq .
          echo $RUN_INFO | jq .databaseId
          gh run -R unknownOrganization/cypress-ci-test --interval 1 --exit-status $(echo $RUN_INFO | jq .databaseId)  watch
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}