name: run cypress test

on:
  workflow_dispatch:

jobs:
  runcy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: trigger cypress test
        run: |
          gh workflow -R unknownOrganization/cypress-ci-test run integration.yaml -r main
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: list cypress test workflow
        run: |
          gh workflow -R unknownOrganization/cypress-ci-test list
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: wait for test success
        uses: lewagon/wait-on-check-action@v1.3.1
        with:
          ref: master
          check-name: test
          repo-token: ${{ secrets.GH_TOKEN }}
          wait-interval: 20